Algumas vezes, você precisa armazenar uma lista de elementos na memória.
Suponha que você esteja escrevendo um aplicativo para gerenciar os seus
afazeres. É necessário armazenar os seus afazeres como uma lista na
memória

* Arrays
:PROPERTIES:
:CUSTOM_ID: arrays
:END:
Usar um array significa que todas as suas tarefas estão armazenadas
contiguamente (uma do lado da outra) na memória. Porém, suponha que você
queira adicionar mais uma tarefa, no entanto, o próximo espaço em
memória está sendo utilizado. É como se você estivesse indo ao cinema
com seus amigos e encontrasse um lugar para sentar, mas outro amigo se
juntasse a vocês e não houvesse lugar para ele. Vocês todos precisariam
se mover e encontrar um lugar onde todos coubessem. Neste caso, você
precisaria solicitar ao computador uma área em que coubessem todas as
suas tarefas então você as moveria para lá

Se outro amigo aparecesse, vocês ficariam sem lugar novamente (e todos
precisariam se mover novamente). Da mesma forma, adicionar novos itens a
um array será muito lento. Uma maneira fácil de resolver isso é
"reservando lugares", mesmo que você tenha três itens na sua lista de
tarefas, você pode solicitar ao computador 10 espaços. Isso é uma boa
maneira de contornar o problema, mas você precisa ficar atento às
desvantagens:

1. Você pode não precisar dos espaços extras, então a memória será
   desperdiçada
2. Você pode precisar adicionar mais de dez itens a sua lista de
   tarefas. então você terá que mover seus itens de qualquer maneira

Arrays são ótimos se você quiser ler elementos aleatórios, pois pode
encontrar qualquer elemento instantaneamente

* Listas Encadeadas
:PROPERTIES:
:CUSTOM_ID: listas-encadeadas
:END:
Com listas encadeadas, seus itens podem estar em qualquer lugar da
memória. Cada item armazena o endereço do próximo item da lista. Um
monte de endereços aleatórios de memória estão ligados. Adicionar um
item a uma lista encadeada é fácil: você o coloca em qualquer lugar da
memória e armazena o endereço do item anterior.

Com as listas encadeadas você nunca precisa mover os seus itens; também
evita outro problema. Listas encadeadas são ótimas se você quiser ler
todos os itens, um de cada vez.

* Inserindo algo no meio da lista
:PROPERTIES:
:CUSTOM_ID: inserindo-algo-no-meio-da-lista
:END:
O que seria melhor se você quisesse inserir elementos no meio de uma
lista: arrays ou listas encadeadas? Usando listas encadeadas, basta
mudar o endereço para o qual o elemento anterior está apontando.

Já para arrays, você deve mover todos os itens que estão abaixo do
endereço de inserção. Se não houver espaço, será necessário mover tudo
para um novo local. Por isso, listas encadeadas são melhores caso você
queira inserir um elemento no meio de uma lista

* Tempos de Execução
:PROPERTIES:
:CUSTOM_ID: tempos-de-execução
:END:
|            | Arrays | Listas |
|------------+--------+--------|
| Leitura    | O(1)   | O(n)   |
| Inserção   | O(n)   | O(1)   |
| Eliminação | O(n)   | O(1)   |

O(n) = tempo de execução linear O(1) = tempo de execução constante

#+begin_quote
Arrays permitem leituras rápidas Listas encadeadas permitem rápidas
inserções e eliminações
#+end_quote
